[package]
name = "auth"
version = "0.1.0"
authors = ["Axel Forsman <axelsfor@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
ring = "^0.13"
actix = "0.7"
actix-web = "0.7"
futures = "0.1"
